### ISSUE TITLE
Do not try to autocomplete if input matches pattern

### ISSUE THREAD

**Issue by lordzsolt** [marlonrichert/zsh-autocomplete#127]
## What do you want?
Exclude input from autocomplete based on regex

## Why do you want this?
I often type `..` or `...` to navigate up the directory structure.
I never type `..` for anything else and the autocomplete suggestions are pretty useless.
I only want autocomplete when I type `../`

## Who else would benefit from this?
Anyone who wants a particular command not to get autocompleted.

## Explain in detail how you would expect this to work
Given the following situation:
Given any regex, for example `^\.{2,}$`

When I perform the following steps:
When I type `..`

Then I expect the following to happen:
Autocompletion not to trigger.

**Comment by marlonrichert** [comment]
Sure, I could add this, but please be advised that it will use [extended glob expressions](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Filename-Generation) instead of regex.

Although, have you tried [setting `min-input`](https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#wait-for-a-minimum-amount-of-input) to 3 yet? Wouldn’t that solve your case, too?

**Comment by lordzsolt** [comment]
I thought about it, but it's not quite the same. For non-`..` input, I want autocomplete to start ASAP.

**Comment by marlonrichert** [comment]
It's there. Enjoy!
