### ISSUE TITLE
key: assignment to invalid subscript range

### ISSUE THREAD

**Issue by Mellbourn** [marlonrichert/zsh-autocomplete#18]
When I try to install it using zinit like this

```
zinit ice wait'2'
zinit load marlonrichert/zsh-autocomplete
```
I get this error

```
/Users/klas.mellbourn/.zinit/plugins/marlonrichert---zsh-autocomplete/zsh-autocomplete.plugin.zsh:87: key: assignment to invalid subscript range
```

I'm on commit b0edf5c

**Comment by marlonrichert** [comment]
It doesn’t work because of this bug in zinit: https://github.com/zdharma/zinit/issues/327

To work around it, don’t load the plugin thru zinit but just `source` the file directly, as per the updated installation instructions: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#installation

You can still use zinit to update the plugin.

**Comment by marlonrichert** [comment]
@Mellbourn There is now a fix available with which you can patch your copy of Zinit until an official fix is released: https://github.com/zdharma/zinit/issues/329#issuecomment-624897560

**Comment by nisavid** [comment]
zdharma/zinit#329 is now resolved, so I believe this can be closed.
