### ISSUE TITLE
Install with antigen failed

### ISSUE THREAD

**Issue by yueyejinghun** [marlonrichert/zsh-autocomplete#198]
* `zsh-autocomplete` version: 817af7c
* Zsh version: 5.8 on Fedora (plus Ubuntu 20.04 and Arch)
* Framework:  Oh My Zsh
* Plugin manager:  antigen (v2.2.2. also tested with antigen nightly build revision date 2018-01-15)
* Error message: 
```zsh
Installing marlonrichert/zsh-autocomplete... Error! Activate logging and try again
```
* Content of .zshrc: 

```zsh
source ~/antigen.zsh
antigen bundle marlonrichert/zsh-autocomplete
antigen apply
```
This issue started to appear in the middle or late February if I remember it right. The first time I installed this plugin with antigen is Jan. 14 because on that day I saw [this](https://stackoverflow.com/a/65461206) answer on StackOverflow. Antigen had no problem install this plugin then. Due to antigen cannot clone a specific branch of a GitHub repo, therefore I am unable to test which branch started to cause this. Now I can manually clone the repo to $HOME/.antigen/bundles/marlonrichert/zsh-autocomplete and it works fine.
[debug_ac_only.log](https://github.com/marlonrichert/zsh-autocomplete/files/6073293/debug_ac_only.log)

**Comment by marlonrichert** [comment]
Like it says: `Activate logging and try again`. 🙂

You can activate logging by setting `ANTIGEN_LOG=~/antigen.log`. Then the real culprit is revealed:
```
Cloning into '/[...]/.antigen/bundles/marlonrichert/zsh-autocomplete'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
```

I renamed the `master` branch to `main`. Instead of cloning `master` explicitly, Antigen should just clone the default branch.

This is a bug in Antigen. Please [file a issue there](https://github.com/zsh-users/antigen/issues).

Or better yet: Since [Antigen is pretty much dead](https://github.com/zsh-users/antigen/graphs/contributors) and your issue unlikely to get fixed, switch to [Znap](https://github.com/marlonrichert/zsh-snap) instead! 😃
