### ISSUE TITLE
History list selection don't match selection content

### ISSUE THREAD

**Issue by remygrandin** [marlonrichert/zsh-autocomplete#243]
* `zsh-autocomplete` version: 473d31a9c949a7e449a9b41fcd57b663c14f9216
* Zsh version: ubuntu/5.8-3ubuntu1
* Framework: Oh My Zsh
* Plugin manager:  none

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% cd /  # Do a bunch of command starting with the same start for history
% cd /etc
% cd /home
.......
```

When afterward I call upon history, the selected history and the displayed one are not the same as they should be.

![image](https://user-images.githubusercontent.com/1934515/114689163-b74bbc00-9d15-11eb-953a-5ae389323a5f.png)

![image](https://user-images.githubusercontent.com/1934515/114689204-c16dba80-9d15-11eb-94fd-16b1571bf579.png)

**Comment by marlonrichert** [comment]
Sorry, but I cannot reproduce this with the steps you've given. Are you sure you haven't left out any steps?

**Comment by achistiakov94** [comment]
@marlonrichert @remygrandin I have the same issue.

Apparently if you do many same commands and then do some different commands, history autocompletion gets screwed up. It's pretty much reproducible.
Consider an example.

That's the setup (we're doing commands here) and history search just by pressing up arrow (without match filter). It works correctly.
```
achistiakov@C02F10Q4ML87 ~ % cat a
achistiakov@C02F10Q4ML87 ~ % cat a
achistiakov@C02F10Q4ML87 ~ % cat a
achistiakov@C02F10Q4ML87 ~ % cat a
achistiakov@C02F10Q4ML87 ~ % cat a
achistiakov@C02F10Q4ML87 ~ % cat b
achistiakov@C02F10Q4ML87 ~ % cat c
achistiakov@C02F10Q4ML87 ~ % cat d
achistiakov@C02F10Q4ML87 ~ % cat d;
...
173 clear
174 cat a
175 cat a
176 cat a
177 cat a
178 cat a
179 cat b
180 cat c
181 cat d
```

Now, if we search by "cat" and hit up arrow, we see this:
```
achistiakov@C02F10Q4ML87 ~ % cat d;
...
174 cat a
175 cat a
176 cat a
```
Doesn't match at all.

I'm completely noob in zsh plugins writing, but from what I understood, the problem is that "matches" and "displays" being completely out of sync here:
https://github.com/marlonrichert/zsh-autocomplete/blob/21.04.24/completion/_autocomplete.history_lines#L71

The dirty quick workaround I've found is to make `displays=( "${(@)matches:/(#m)*/${(r:COLUMNS-1:)MATCH}}" )` right before `compadd` line. In this case `displays` becomes as just nicer representation of actual `matches`. We're losing the line number this way though, but I don't really care about that anyway.

**Comment by marlonrichert** [comment]
Sure, it's clear that `matches` and `displays` are out of sync, but I still cannot reproduce the issue. Here's what I did:
```zsh
$ cd $(mktemp -d)
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ PS1='%# ' HOME=$PWD exec zsh -f 
% source /Users/marlon/Git/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% cat a
cat: a: No such file or directory
% cat a 
cat: a: No such file or directory
% cat a 
cat: a: No such file or directory
% cat a 
cat: a: No such file or directory
% cat a 
cat: a: No such file or directory
% cat b
cat: b: No such file or directory
% cat c
cat: c: No such file or directory
% cat d
cat: d: No such file or directory
% 
```
Then I pressed <kbd>Up</kbd> to open the history menu. Works fine. All in sync.

@achistiakov94 @remygrandin Please use the above to create a test case with which I can actually use to reproduce the problem. If I cannot reproduce it, I cannot fix it.

**Comment by remygrandin** [comment]
I think I understood the miscommunication that there was. The issue arrise when doing and up to bringthe history **after** typing the start of the command.
I have done your exact example, if I type "cat" then press up, the display issue is here.

**Comment by marlonrichert** [comment]
@remygrandin Thanks! Now I can reproduce it.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by achistiakov94** [comment]
Just tested it, now it works good.
Thank you for the fix!
