### ISSUE TITLE
filter completion based on fuzzy search help text

### ISSUE THREAD

**Issue by tshu-w** [marlonrichert/zsh-autocomplete#313]
## What do you want?
It would be much appreciated if we could filter completion based on fuzzy search help text like https://github.com/Aloxaf/fzf-tab.

<img width="1476" alt="Screen Shot 2021-07-29 at 22 04 06" src="https://user-images.githubusercontent.com/13161779/127506921-b1ad9fc9-cff5-494d-a694-d147eed3928a.png">

## Explain in detail how you would expect this to work
Given the following situation:
* If a command has many options while users are not familiar with it, it will be much helpful if we could filter completion based on fuzzy search options help text.

When I perform the following steps:
1. type a command
2. (optional) type some keybinds
3. type text or fallback to fzf-tab.

Then I expect the following to happen:
* complete was filter by help text.

**Comment by tshu-w** [comment]
BTW, how do I change the Multi-select shortcut（Ctrl-Space）, I'm not familiar with zsh yet.

**Comment by marlonrichert** [comment]
Filtering is not possible, but you can do full-text search (that is, search through _all_ text displayed) by doing the following:
1. Press ⬇️ to start menu selection.
2. Press <kbd>⌃</kbd><kbd>S</kbd> to start searching.

See the Readme a for a [full list of keybindings](https://github.com/marlonrichert/zsh-autocomplete#key-bindings).

Otherwise, this is not a feature of `zsh-autocomplete`, but rather a feature of `zsh` itself. Feel free to submit a feature request on the [`zsh` mailing lists](https://zsh.sourceforge.io/Arc/mlist.html).

**Comment by marlonrichert** [comment]
> BTW, how do I change the Multi-select shortcut（Ctrl-Space）, I'm not familiar with zsh yet.

<kbd>⌃</kbd><kbd>␣</kbd> for multiselect is [defined here](https://github.com/marlonrichert/zsh-autocomplete/blob/1db1177a6b6cd4c7eb65ada856ecaaff70fb400b/module/.autocomplete.key-binding#L69). For documentation, see the `zsh` manual:
* [`bindkey` builtin](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Zle-Builtins)
* [`zsh/complist` module > menu selection](https://zsh.sourceforge.io/Doc/Release/Zsh-Modules.html#Menu-selection)

**Comment by tshu-w** [comment]
Thanks for the quick reply to such a newbie question.

**Comment by marlonrichert** [comment]
No problem. And feel free to [give something back](https://github.com/sponsors/marlonrichert). 😉
