### ISSUE TITLE
Freezing after first character, only responsive after CTRL+C

### ISSUE THREAD

**Issue by stepotronic** [marlonrichert/zsh-autocomplete#336]
* `zsh-autocomplete` version: current master
* Zsh version: zsh 5.8 (x86_64-apple-darwin20.0)
* Framework: "none" 
* Plugin manager: "none"
* Operating system: macOs Big Sur

I sadly cannot even give you any other output.
Installed following the instructions in the README and just used source to load it. I used the special instructions in this bug ticket as well. 

As soon as I type one character it already freezes. e.g. "l" to start with "ls" and it becomes unresponsive. I then can press CTRL+C to kill the process type another character and it seems to run normally. => As soon as i get to a 2nd character it is ok.

Also interesting: It does not seem to happen to every character. E.g "e" works fine and shows me a handful of commands instantly. (other characters that work: b, j, o, q, v, x, y)
Tried to figure out if that is somehow related to commands that need access to the filesystem since cd and ls were the ones where i noticed first but I could not find.

The .`zshrc` is now completely empty and started new sessions to make sure nothing interferes. Same issue.

KR
Stepo

**Comment by paxtonfitzpatrick** [comment]
* `zsh-autocomplete` version: f8899c9 (current `main`)
* Zsh version: `zsh 5.7.1 (x86_64-apple-darwin19.0)`
* Framework: Oh My Zsh (also tested with none)
* Plugin manager: Oh My Zsh (also tested with none)
* Operating system: macOS Catalina 10.15.7
* I also can't produce any meaningful output, but steps to reproduce are described below

Just to add some additional info, I started having this issue as well after pulling updates in the hopes of fixing an unrelated issue. It seems to have been introduced in cd4ad82 -- reverting to d17e479 works just fine, but cd4ad82 and f8899c9 are both broken. 

As far as I can tell, it happens when the suggestions generated take up more lines than are available, and you'd normally be prompted with `(MORE)`.  E.g., partial inputs that generate hundreds of lines like `ps ` (with trailing space) or  `$` (shows all parameters) will hang, and those that don't (`ech`, `buil`, etc.) will not.  I tested out a few inputs that generate a reasonable number of lines (e.g., `docker-compose `; note trailing space; completion plugin [here](https://docs.docker.com/compose/completion/#zsh)) and was able to make it hang or succeed by resizing my terminal window to have fewer or more lines than the suggestions took up.

**Comment by marlonrichert** [comment]
@paxtonfitzpatrick Thanks for the detailed info! I will test it today on macOS.

**Comment by marlonrichert** [comment]
OK, I can reproduce it. Let me see what I can do.

**Comment by marlonrichert** [comment]
Fixed! 🙂

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 💝

**Comment by marlonrichert** [comment]
Fixed! 🙂

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 💝
