### ISSUE TITLE
Arrow Keys not working with default settings

### ISSUE THREAD

**Issue by vale46** [marlonrichert/zsh-autocomplete#365]
Up arrow key at terminal prompt (with default zsh-autocomplete settings) shows last command only, instead of history of 16. Down arrow key doesn't do anything.

When reproducing the problem (as directed),  in new shell, arrow keys work as expected.

```zsh
>git -C ~zsh-autocomplete log --oneline -n1
a37ca02 (HEAD -> main, origin/main, origin/HEAD) Fix a bug in correct/approximate completer

>print -l $_autocomplete__funcfiletrace
(empty-string)

>print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
debian linux-gnu /usr/bin/zsh zsh debian/5.8-10
```

### Steps to reproduce

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1="%# " PS2="  "; setopt transientrprompt
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH FPATH=$FPATH TERM=$TERM zsh -d
```

**Comment by vale46** [comment]
discovered that I have to source zsh-autocomplete.plugin.zsh a 2nd time, towards the end of my .zshrc, for arrow keys to work as expected.

**Comment by marlonrichert** [comment]
> When reproducing the problem (as directed), in new shell, arrow keys work as expected.

That means the problem is somewhere in your dotfiles and not in `zsh-autocomplete`. Try commenting out lines from your `.zshrc` file until you find the one that causes the problem.

> discovered that I have to source zsh-autocomplete.plugin.zsh a 2nd time, towards the end of my .zshrc, for arrow keys to work as expected.

That means something else in your dotfiles is overriding `zsh-autocomplete`'s keybindings. Again, try commenting out lines from your `.zshrc` file until you find the one that causes the problem.

**Comment by vale46** [comment]
thx for the feedback.

when I disable `oh-my-zsh` (which I'm using along with `zsh-autocomplete`) arrow keys start working. Still going thru `oh-my-zsh` setup script to isolate what I'm seeing. Given the popularity of `oh-my-zsh` in `zsh` setups, anyone else experience this issue with GNOME terminal?

Oddly enough when I replicate the same `zsh` setup on a different PC, running W10 with `msys2` in mintty terminal, the arrow keys work fine.

**Comment by marlonrichert** [comment]
Can you share your `.zshrc` file? Then I can help you find what's wrong.

**Comment by martaver** [comment]
Also experiencing this problem on ZSH in MacOS.

If I `source $ZSH/oh-my-zsh.sh` before I install zsh-autocomplete (with znap), history works.
If I source it afterwards, history is broken.

Kind of annoying because it means I have to define my plugins and configurations in a particular order.

Incidentally, if I don't source OMZ at all, then the context info under the prompt breaks, and is replaced by `no such 'suffix alias'.

**Comment by martaver** [comment]
My `.zshrc` (minimal repro)

```
export ZSH="/Users/martaver/.oh-my-zsh"

# Download Znap, if it's not there yet.
[[ -f ~/git/zsh-snap/znap.zsh ]] ||
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ~/git/zsh-snap

source ~/git/zsh-snap/znap.zsh  # Start Znap

znap source marlonrichert/zsh-autocomplete

source $ZSH/oh-my-zsh.sh
```

You can get the desired effect by moving around `source $ZSH/oh-my-zsh.sh` or commenting it out.

**Comment by marlonrichert** [comment]
> If I `source $ZSH/oh-my-zsh.sh` before I install zsh-autocomplete (with znap), history works.
> If I source it afterwards, history is broken.

Well, yes, because OMZ then overrides `zsh-autocomplete`'s keybindings. So, don't source them in that order. 🙂

Alternatively, since you are using Znap, you can opt to not `source $ZSH/oh-my-zsh.sh` but instead use `znap source` to [load only those parts of OMZ that you actually want](https://github.com/marlonrichert/zsh-snap/blob/4a35a4b856e67cdcb13bd37f36fce3f20d34a83e/.zshrc#L40) and leave out [OMZ's keybindings](https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/key-bindings.zsh).

> Incidentally, if I don't source OMZ at all, then the context info under the prompt breaks, and is replaced by `no such 'suffix alias'.

Can you open separate issue for that? Then I will have a look at it.
