### ISSUE TITLE
run-tests.zsh:2: clitest not found

### ISSUE THREAD

**Issue by BK-STAR77** [marlonrichert/zsh-autocomplete#387]
OS BIG SUR 11.6.2

bkstar@Mac-mini-de-BK ~ % omz reload
/Users/bkstar/.oh-my-zsh/custom/plugins/zsh-autocomplete/run-tests.zsh:2: clitest not found
bkstar@Mac-mini-de-BK ~ %

thank you for help

**Comment by marlonrichert** [comment]
That’s a bug in either Oh-My-Zsh or your own dotfiles. That script should not be run on startup, since it’s not a plugin file. Please [file a bug in the Oh-My-Zsh repo](https://github.com/ohmyzsh/ohmyzsh/issues/new?assignees=&labels=Bug&template=bug_report_omz.yml) or fix the problem in your dotfiles.
