### ISSUE TITLE
_zsh_autosuggest_highlight_reset:3: maximum nested function level reached

### ISSUE THREAD

**Issue by rjcoelho** [marlonrichert/zsh-autocomplete#43]
On every prompt I get
```
_zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?
```

Here is my zshrc 
```
fpath=($fpath "$ZDOTDIR/plugins/pure")
promptinit
prompt pure
source "$ZDOTDIR/plugins/syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$ZDOTDIR/plugins/autosuggestions/zsh-autosuggestions.zsh"
source "$ZDOTDIR/plugins/autocomplete/zsh-autocomplete.zsh"
```

If I set prompt after sourcing autocomplete all is ok

**Comment by marlonrichert** [comment]
I don't know exactly what `promptinit` does, but it by itself seems to break half of my keybindings. 🙁

I'll have to investigate further how to work around this.

**Comment by marlonrichert** [comment]
Wow, it took quite some time and effort to figure out what went wrong with this one! 😰

It turns out the real minimal test case is this:
```shell
fpath+=( path/to/pure.zsh )
autoload -Uz promptinit && promptinit
prompt pure
source path/to/zsh-syntax-highlighting.zsh
autoload -Uz add-zle-hook-widget
add-zle-hook-widget line-finish :
```

**Comment by marlonrichert** [comment]
@rjcoelho I pushed in a fix on the `dev` branch. Can you please checkout that branch and tell if it works for you?

**Comment by rjcoelho** [comment]
That was quick .. I don't have installed now. Maybe add some sort of test cases you this lib?

**Comment by marlonrichert** [comment]
Of course I tested it. But I want confirmation that it works for you, too. 🙂

**Comment by marlonrichert** [comment]
The fix is now available on the `master` branch.

**Comment by Geeky-nutcracker** [comment]
Sorry for my novice approach but I just couldn't get over this error. Since the error is kinda similar I'm mentioning it in here itself. The error is `_zsh_autosuggest_widget_modify:1: maximum nested function level reached; increase FUNCNEST?`. I'm getting it at every prompt.

I've downloaded this git repository and used the following in my `.zshrc`:
`source ${HOME}/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh`
But this didn't help me out.

As you mention that the fix is available in the `master` branch but I couldn't locate it. Any sort of help would be totally appreciable.

**Comment by marlonrichert** [comment]
@mushi-nova Can you share your `~/.zshrc` file? It's kind of hard to tell what is the problem without any further info on your setup.

Also, the `master` branch is the default you get when you clone any Git repository. So, you should have the fix already.

**Comment by marlonrichert** [comment]
@mushi-nova But also: Could you try out the `dev` branch and see if you have the problem there, too? You can do this as follows:
1. `cd ${HOME}/.zsh/zsh-autocomplete/`
2. `git pull`
3. `git checkout dev`
4. Restart your terminal.

**Comment by mushi-nova** [comment]
Sorry for the trouble. Actually this error almost wrecked zsh since I made a stupid mistake. So I reinstalled everything from the very beginning and everything was okay. And as far as your as previous answer, yeah I went into the `master` branch and read that it was already solved with a fix. Anyway, I'm still unaware of the reason why that happened. Thanks for the reply. If you still wish to see my previous .zshrc file then I would be happy to show it to you since I have the preserved
