### ISSUE TITLE
Have the history menu cycle the entire history, with the same filtering as `^R`

### ISSUE THREAD

**Issue by marlonrichert** [marlonrichert/zsh-autocomplete#550]
> when doing history search, if the command I'm looking for isn't in the 16 displayed, how can search further back? If I keep pressing "up arrow", it just cycles back to the bottom of the list.

_Originally posted by @wtfzambo in https://github.com/marlonrichert/zsh-autocomplete/issues/459#issuecomment-1447001177_

**Comment by marlonrichert** [comment]
Now available on `main`. @wtfzambo Please update and let me now if it doesn't work for you.

**Comment by wtfzambo** [comment]
@marlonrichert fantastic, it works great! I'll keep you posted if I find anything strange.

I have another question and a suggestion:
Is it possible to control the matching behavior when doing history search? For example instead of fuzzy search, match on the word being typed exactly? I'll show what I mean: in the gif, you see that history search matches the word `poetry` only at the very end, whereas before, it also show unrelated commands.

<p align="center">
<img src="https://user-images.githubusercontent.com/47462792/230342398-f152076c-f6e0-4314-a06c-899453e93aa0.gif" width=60%>
</p>

As for what regards the suggestion: I think it would be cool if history search would show only unique entries. Imagine something like this:

![image](https://user-images.githubusercontent.com/47462792/230343178-447d011e-2eef-48a5-bd65-97187d9c3bc6.png)

**Comment by marlonrichert** [comment]
> Is it possible to control the matching behavior when doing history search? For example instead of fuzzy search, match on the word being typed exactly?

I'm further fine-tuning it as we speak. Not sure yet how I could make it configurable in a meaningful, understandable way. Let's talk again after I've released the next version of this feature.

> I think it would be cool if history search would show only unique entries. 

If you want to see unique entries only, add `setopt HIST_FIND_NO_DUPS` to your `.zshrc` file.

**Comment by wtfzambo** [comment]
Thanks man, you're the best!

**Comment by emilyst** [comment]
It looks like [you added some code that looks for the option `HIST_FIND_NO_DUPS` and uniques the list of suggested history if it's set](https://github.com/marlonrichert/zsh-autocomplete/commit/0edbecaa09967a4442b0944d290726c4b851637f) (among other things). This makes sense, but I think it may cause an issue for people who have this option set and who have large histories.

Unfortunately, I've accumulated over 44K history entries (since I never throw history away). Therefore, `_autocomplete.history_lines` takes about four minutes to run on my system (and then eventually seems to fail anyways).

Since I've had `HIST_FIND_NO_DUPS` set all along, it isn't really helping me to unique the suggestions. I imagine most of the people with `HIST_FIND_NO_DUPS` set will _not_ benefit from this, since they're unlikely to have duplicate entries in their history file. And those without it set are more likely to benefit from it.

Maybe the right way to go is to unique that list if it's _not_ set?

**Comment by marlonrichert** [comment]
`HIST_FIND_NO_DUPS` does not prevent dups from being saved to hist file. It only prevents the built-in hist widgets from showing dups. `HIST_SAVE_NO_DUPS` prevents saving dups to file. See https://zsh.sourceforge.io/Doc/Release/Options.html#History
