### ISSUE TITLE
Enable suggestions for aliases

### ISSUE THREAD

**Issue by benwoodward** [marlonrichert/zsh-autocomplete#60]
### Is your feature request related to a problem?
Typing `git c` will yield a long list of git commands starting with 'c':

![image](https://user-images.githubusercontent.com/1472981/84846202-64c45380-b0a2-11ea-8e1d-c4b212f3a8f8.png)

However, when invoking `git` via `g` alias (`alias g='git'`) does not yield git-related results:
![image](https://user-images.githubusercontent.com/1472981/84846322-9e955a00-b0a2-11ea-985b-59ce63018a00.png)

### Describe the solution you'd like
Ideally I'd like the plugin to automatically detect that an alias is being used, and look up the relevant results.

**Comment by marlonrichert** [comment]
@benwoodward It's virtually impossible for me to figure out which of a user's aliases should map to which commands, since aliases can include multiple commands and all other kinds of nonsense. However, what I _can_ do is automatically expand aliases. So, for example, in your case, if you type <kbd>g</kbd> plus <kbd>space</kbd>, then it will automatically expand to `git `, which will then result in Zsh offering the correct completions. This feature is now available in the `dev` branch. Please try it out.

**Comment by marlonrichert** [comment]
I just discovered that the `COMPLETE_ALIASES` option did _not_ do what I think it does. Unsetting it turns out to be enough to get this to work.

**Comment by marlonrichert** [comment]
Fixed in `master`.

**Comment by benwoodward** [comment]
Hell yeah! Nice work! Thank you.
