### ISSUE TITLE
Quickly typing Enter from completion executes, without completion

### ISSUE THREAD

**Issue by yuki-ycino** [marlonrichert/zsh-autocomplete#62]
### Describe the bug

Input quickly `git diff .vimr<Tab><Enter>`, It runs the git diff command as a `.vimr` with no completion.
If press Tab and wait a little, vimrc will be completed normally.

### Expected behavior

Appropriate completion is also provided for quick input.

### Screenshots

![Kapture 2020-06-25 at 17 24 15](https://user-images.githubusercontent.com/5423775/85684313-f66a3b80-b708-11ea-81dc-a4b6aa5a44a6.gif)

### Desktop
 - MacOS Catalina 10.15.5
 - zsh 5.8 (x86_64-apple-darwin19.3.0)
 - Plugin version: c3359401f81bcfe26a9238a961391a05e3972e3b

**Comment by marlonrichert** [comment]
I cannot reproduce this, not on `master` and not on `dev`.

Can you please do 
```shell
cd "$(mktemp -d)"
ZDOTDIR=$PWD HOME=$PWD zsh -df
source path/to/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
and tell me if the problem persists?

If it doesn't, then the problem is likely in your config somewhere. In the sub shell created above, you can try pasting in and running the lines from your `.zshrc` one by one, until you find which one breaks it. Once you find that out, then I can try to fix it for you.

**Comment by marlonrichert** [comment]
Closed because I cannot reproduce this and I haven't heard back from @yuki-ycino.

**Comment by marlonrichert** [comment]
@yuki-ycino Does it look to you like #80 is the same issue?
