### ISSUE TITLE
Sort longest prefix matches first

### ISSUE THREAD

**Issue by xoriade** [marlonrichert/zsh-autocomplete#70]
### Is your feature request related to a problem? Please describe.
When I enter `vim .zshr`, I get the completion list `.zsh_history .zshrc`.

### Describe the solution you'd like
I want to get the list in order of longest prefix matches, so in this case `.zshrc .zsh_history`.
While it's very crucial in my opinion for the actual prefix, I assume it would be nice to always sort by the appearance of actual matching characters. So for example for `xyz` match `bxycz` before `axcyz` or `acxyz`.

### Describe alternatives you've considered
As this essentially breaks tab completion for me, there really is none for me besides not using the plugin.

**Comment by marlonrichert** [comment]
@xoriade Can you check out the `dev` branch and try if you like the completion behavior there? I've made some changes.

**Comment by xoriade** [comment]
On `dev` this is solved :+1: Thanks!

It seems now *fuzzy* (as in subsequence instead of substring, substring match instead of prefix match) results aren't listed at all when non-fuzzy counterparts exist. This certainly fixes the original problem.
However, it does conflict with the expected behavior coming from `master` that one gets shown all matching results, fuzzy or not. If this is for performance or dev-effort reasons, I'm perfectly fine with it ;-) Otherwise the results one gets on master, sorted by some matching-position based metric, would probably be better as it would provide more consistent behavior: In that case the user would know whether fuzzy matches exist or not and could see what he has to type in order to quickly filter the matches in order to only press <tab> once for his desired result.
Even if all matches are fuzzy, alphabetical order is far from optimal, for example when typing `vim cz`, I'd expect the entry `acxyz` (some file) to get a higher priority than `.oh-my-zsh/custom/plugins/zsh-autocomplete/` which isn't the case on `dev` just now.

**Comment by marlonrichert** [comment]
> for example when typing `vim cz`, I'd expect the entry `acxyz` (some file) to get a higher priority than `.oh-my-zsh/custom/plugins/zsh-autocomplete/` which isn't the case on `dev` just now.

Can you share a video recording of that here, so I can see what’s going on? I cannot reproduce it.

**Comment by marlonrichert** [comment]
> However, it does conflict with the expected behavior coming from `master` that one gets shown all matching results, fuzzy or not. If this is for performance or dev-effort reasons, I'm perfectly fine with it ;-) Otherwise the results one gets on master, sorted by some matching-position based metric, would probably be better as it would provide more consistent behavior:

Unfortunately, Zsh’s completion system provides very little control over the ordering of the results. So, there’s nothing I can do about it _easily._ I do have some ideas on how I could work around it, but that will require more investigation by trial and error.

> In that case the user would know whether fuzzy matches exist or not and could see what he has to type in order to quickly filter the matches in order to only press <tab> once for his desired result.

That was my thought originally, too, which is why I made it work that way originally. However, this does have some drawbacks.

The first is that often the completion that feels to the user as being the best match was often not the first listed. Many users have complained about this, in various ways.

The second problem is that, in many cases, trying to show _all_ possible matches will ironically result in _no_ matches being shown at all, because they simply don’t fit on screen. In addition, many users have expressed to me that they don’t need to see all possible completions; they just want to see the ones that matter to them.

So, to combat these two problems, I have decided to show less completions at once, so that
* the result that the user is expecting to come first will actually be listed first, and
* the list of completions is more likely to fit on screen.

However, for those cases where you do want to see (nearly) all completions, you can <kbd>Shift</kbd><kbd>Tab</kbd> to force (most) hidden completions to be revealed (on the `dev` branch, that is). Please give it a try and let me know if that helps. 🙂
