### ISSUE TITLE
setopt/unsetopt

### ISSUE THREAD

**Issue by z0rc** [marlonrichert/zsh-autocomplete#9]
The plugin isn't the right place to change setopts, especially something like AUTO_CD and BEEP.

Please use [LOCAL_OPTIONS](http://zsh.sourceforge.net/Doc/Release/Options.html#index-NOLOCALOPTIONS) or even `emulate -L zsh`, so you can explicitly define needed option in functions without touching user configuration.

**Comment by marlonrichert** [comment]
I won't use `localoptions`, because the whole point of this plugin is to make completion work well out of the box. Some options will need to be set for this.

However, I will consider removing some to make the plugin slightly less opinionated, as long as it doesn't worsen the UX too much. Thanks for your input.

**Comment by z0rc** [comment]
If you need some specific options to be set, you can do this similarly to https://github.com/Aloxaf/fzf-tab/pull/16.

**Comment by marlonrichert** [comment]
Thanks, there's just one problem with this:

> There is one exception: _main_complete must be called with user-defined options because its results are option-dependent. For example, _main_complete ignores files whose names begin with . unless dot_glob is set.

Most of my code revolves around `_main_complete`. So, I'm not sure it makes sense to use `localoptions` here.

For example, I have actually tried to do `setopt localoptions nobeep` in my functions, but that did not get rid of all the beeping that `list-choices` does otherwise.

Perhaps @romkatv would like to comment on this?

**Comment by romkatv** [comment]
> Perhaps @romkatv would like to comment on this?

Not really.

**Comment by marlonrichert** [comment]
@z0rc I now use `emulate -L zsh` and `localoptions` in all other cases. Plus, I moved all the options I need into an array that the user can override. Please check it out and let me know if this resolves the issue for you. 🙂

**Comment by marlonrichert** [comment]
I think this should be resolved now. Closing the issue. Let me know if it needs to be reopened.
